DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS graphs;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE graphs (
    user_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    expression TEXT NOT NULL,
    color TEXT NOT NULL
);